name: Build for testing Code Coverage

on:
  push:
    branches:
      - master
env:  
  JAVA_VERSION: '8'
  MAVEN_RUN_COMMAND: mvn clean install
  AZURE_WEBAPP: 'new-javaapp'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    
    - name: Testing
      run: mvn clean test
    - name: Build with the Maven
      run: ${{ env.MAVEN_RUN_COMMAND }}
      
       
        
    - name: Upload Unit Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results 
        path: '${{ github.workspace }}/target/*.xml'
  
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: java-app
    
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts
    
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: artifacts/**/*.xml
    
   
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '.'
